### ISSUE TITLE
Cannot Search for Series or Stories

### ISSUE THREAD

**Issue by insanetron75** [chadicus/marvel-api-client#38]
Hello, 

I am having an issue using the `client->search()` function to retrieve stories or series.

```php
protected function getItems(Character $character, $itemType)
{
    $comicWrapper = $this->client->search($itemType, [
        'characters' => $character->id,
        'limit'      => 40
    ]);
    return $comicWrapper->getData()->getResults();
}
```
## Expected Behavior
if `$itemType = 'comics` this function returns an array or comics
if `$itemType = 'events` this function returns an array or events
if `$itemType = 'stories'` this function returns an array or stories
if `$itemType = 'series'` this function returns an array or series

## Actual Behavior
if `$itemType = 'comics` this function returns an array or comics
if `$itemType = 'events` this function returns an array or events

if `$itemType = 'stories'` && `$itemType = 'series'`  produce the following error:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Chadicus\Marvel\Api\Entities\AbstractEntity::fromArray() must be of the type array, null given in /home/tim/ContinuumTest/vendor/chadicus/marvel-api-client/src/Entities/AbstractEntity.php:109
Stack trace:
#0 [internal function]: Chadicus\Marvel\Api\Entities\AbstractEntity::fromArray(NULL)

#1 /home/tim/ContinuumTest/vendor/dominionenterprises/filter/src/Filterer.php(166): call_user_func_array('\\Chadicus\\Marve...', Array)

#2 /home/tim/ContinuumTest/vendor/chadicus/marvel-api-client/src/Filterer.php(53): DominionEnterprises\Filterer::filter(Array, Array, Array)

#3 /home/tim/ContinuumTest/vendor/chadicus/marvel-api-client/src/Entities/AbstractEntity.php(29): Chadicus\Marvel\Api\Filterer::filter(Array, Array, Array)

#4 /home/tim/ContinuumTest/vendor/chadicus/marvel-api-client/src/Entities/AbstractEntity.php(96): Chadicus\Marvel\Api\Entities\AbstractEntity->__construct(Array)

#5 [internal function]: Chadicus\Marvel\Ap in /home/tim/ContinuumTest/vendor/chadicus/marvel-api-client/src/Entities/AbstractEntity.php on line 109

```

**Comment by chadicus** [comment]
@insanetron75 This should be fixed with v3.0.1. Please upgrade and let me know if the issue persists.
